apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-configmap
data:
  TODO_BACKEND_PORT: "8080"
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: ""
  WIKI_URL: "https://en.wikipedia.org/wiki/Special:Random"
  NATS_URL: "nats://my-nats:4222"
