apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resourcedefinition.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - gateway.yaml
  - dummysite.yaml
