apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - manifests/postgres.yaml
  - manifests/knative.yaml
  - manifests/service.yaml
images:
  - name: ping-pong-image
    newName: ramanan98/ping-pong
    newTag: 6e30c743a52965ec42c117dffbaa06c2097654f9
