apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- manifests/gateway.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/route.yaml
images:
- name: ping-pong-image
  newName: ramanan98/ping-pong
  newTag: 6e30c743a52965ec42c117dffbaa06c2097654f9
