apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: image-write
          image: ramanan98/image-write@sha256:e09070ff84bac85d72c95858f56333eeb7d77e9e28742b5d753c00e5ecbb4934
          env:
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: IMAGE_URL
            - name: IMAGE_WRITE_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: IMAGE_WRITE_PATH
            - name: SLEEP_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: SLEEP_INTERVAL
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
        - name: image-read
          image: ramanan98/image-read:latest
          env:
            - name: IMAGE_READ_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: IMAGE_READ_PORT
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: BACKEND_HOST
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: BACKEND_PORT
            - name: IMAGE_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: IMAGE_PATH
            - name: HTML_FILE
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: HTML_FILE
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
