apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: image-write
          image: image-write-image
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
          env:
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: IMAGE_URL
            - name: IMAGE_WRITE_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: IMAGE_WRITE_PATH
            - name: SLEEP_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: SLEEP_INTERVAL
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
        - name: image-read
          image: image-read-image
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: IMAGE_READ_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: IMAGE_READ_PORT
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: BACKEND_HOST
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: BACKEND_PORT
            - name: IMAGE_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: IMAGE_PATH
            - name: HTML_FILE
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: HTML_FILE
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
