apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/route.yaml
images:
- name: log-output-image
  newName: ramanan98/log-output
  newTag: 0bdc6648650d14a606c4ee4197c9816455d42cb8
