apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-configmap
  namespace: project
data:
  TODO_BACKEND_PORT: "8080"
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: ""
