apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wiki-route
  namespace: exercises
spec:
  parentRefs:
    - name: dwk-material-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /wiki
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: wiki-svc
          port: 80
